[package]
name = "sloop"
version = "0.1.0"
authors = ["RobbieClarken <robbie.clarken@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
rss = "1.8"
rusoto_core = "0.41"
rusoto_s3 = "0.41"
structopt = "0.3"

[dev-dependencies]
roxmltree = "0.7"
